### ISSUE TITLE
I tried to tweak this intoa  flask aplication adn I get the following, any idea?

### ISSUE THREAD

**Issue by connorv001** [AdirthaBorgohain/intelliweb-GPT#2]
```
<div class="detail">
  <p class="errormsg">ValueError: signal only works in main thread of the main interpreter
</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  <h3></h3>
  <ul><li><div class="frame" id="frame-140663172345616">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/flask/app.py"</cite>,
      line <em class="line">2551</em>,
      in <code class="function">__call__</code></h4>
  <div class="source "><pre class="line before"><span class="ws">    </span>def __call__(self, environ: dict, start_response: t.Callable) -&gt; t.Any:</pre>
<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;The WSGI server calls the Flask application object as the</pre>
<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>
<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>
<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;</pre>
<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)</pre></div>
</div>

<li><div class="frame" id="frame-140663172342592">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/flask/app.py"</cite>,
      line <em class="line">2531</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source "><pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">                </span>error = e</pre>
<pre class="line current"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre>
<pre class="line after"><span class="ws">                </span>raise</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-140663172348416">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/flask/app.py"</cite>,
      line <em class="line">2528</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source "><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws">        </span>error: t.Optional[BaseException] = None</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>error = e</pre>
<pre class="line after"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre></div>
</div>

<li><div class="frame" id="frame-140663172349200">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/flask/app.py"</cite>,
      line <em class="line">1825</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source "><pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line current"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre>
<pre class="line after"><span class="ws">        </span>self,</pre>
<pre class="line after"><span class="ws">        </span>rv: t.Union[ft.ResponseReturnValue, HTTPException],</pre></div>
</div>

<li><div class="frame" id="frame-140663172345952">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/flask/app.py"</cite>,
      line <em class="line">1823</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source "><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line current"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line after"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre></div>
</div>

<li><div class="frame" id="frame-140663172341584">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/flask/app.py"</cite>,
      line <em class="line">1799</em>,
      in <code class="function">dispatch_request</code></h4>
  <div class="source "><pre class="line before"><span class="ws">            </span>and req.method == &#34;OPTIONS&#34;</pre>
<pre class="line before"><span class="ws">        </span>):</pre>
<pre class="line before"><span class="ws">            </span>return self.make_default_options_response()</pre>
<pre class="line before"><span class="ws">        </span># otherwise dispatch to the handler for that endpoint</pre>
<pre class="line before"><span class="ws">        </span>view_args: t.Dict[str, t.Any] = req.view_args  # type: ignore[assignment]</pre>
<pre class="line current"><span class="ws">        </span>return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def full_dispatch_request(self) -&gt; Response:</pre>
<pre class="line after"><span class="ws">        </span>&#34;&#34;&#34;Dispatches the request and on top of that performs request</pre>
<pre class="line after"><span class="ws">        </span>pre and postprocessing as well as HTTP exception catching and</pre>
<pre class="line after"><span class="ws">        </span>error handling.</pre></div>
</div>

<li><div class="frame" id="frame-140663172348640">
  <h4>File <cite class="filename">"/home/shubham/1-lang/fluff/intelliweb-GPT/example_usage.py"</cite>,
      line <em class="line">18</em>,
      in <code class="function">answer_question</code></h4>
  <div class="source "><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span>@app.route(&#39;/generate_answer&#39;, methods=[&#39;POST&#39;])</pre>
<pre class="line before"><span class="ws"></span>def answer_question():</pre>
<pre class="line before"><span class="ws">    </span>query = request.json[&#39;query&#39;]</pre>
<pre class="line before"><span class="ws">    </span>use_serper_api = request.json.get(&#39;use_serper_api&#39;, True)</pre>
<pre class="line current"><span class="ws">    </span>result = generate_answer(query, use_serper_api)</pre>
<pre class="line after"><span class="ws">    </span>return jsonify(result)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>if __name__ == &#39;__main__&#39;:</pre>
<pre class="line after"><span class="ws">    </span>app.run(debug=True,host=&#39;0.0.0.0&#39;,port=8082,threaded=False)</pre></div>
</div>

<li><div class="frame" id="frame-140663172346400">
  <h4>File <cite class="filename">"/home/shubham/1-lang/fluff/intelliweb-GPT/intelliweb_GPT/generate.py"</cite>,
      line <em class="line">70</em>,
      in <code class="function">generate_answer</code></h4>
  <div class="source "><pre class="line before"><span class="ws">                </span>urls = [r for r in res]</pre>
<pre class="line before"><span class="ws">            </span>QA_PROMPT = QuestionAnswerPrompt(QA_PROMPT_WEB_TMPL)</pre>
<pre class="line before"><span class="ws">            </span>CHAT_REFINE_QA_PROMPT_LC = ChatPromptTemplate.from_messages(CHAT_REFINE_QA_PROMPT_WEB_TMPL_MSGS)</pre>
<pre class="line before"><span class="ws">            </span>REFINE_QA_PROMPT = RefinePrompt.from_langchain_prompt(CHAT_REFINE_QA_PROMPT_LC)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line current"><span class="ws">        </span>documents = reader.load_data(urls=urls)</pre>
<pre class="line after"><span class="ws">        </span>index = GPTSimpleVectorIndex.from_documents(documents, use_async=True, service_context=service_context)</pre>
<pre class="line after"><span class="ws">        </span>response = asyncio.run(</pre>
<pre class="line after"><span class="ws">            </span>index.aquery(query, response_mode=&#39;tree_summarize&#39;, similarity_top_k=5,</pre>
<pre class="line after"><span class="ws">                         </span>text_qa_template=QA_PROMPT, refine_template=REFINE_QA_PROMPT)</pre>
<pre class="line after"><span class="ws">        </span>)</pre></div>
</div>

<li><div class="frame" id="frame-140663172343936">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/llama_index/readers/web.py"</cite>,
      line <em class="line">102</em>,
      in <code class="function">load_data</code></h4>
  <div class="source "><pre class="line before"><span class="ws">            </span>downloaded = trafilatura.fetch_url(url)</pre>
<pre class="line before"><span class="ws">            </span>if not downloaded:</pre>
<pre class="line before"><span class="ws">                </span>if self.error_on_missing:</pre>
<pre class="line before"><span class="ws">                    </span>raise ValueError(f&#34;Trafilatura fails to get string from url: {url}&#34;)</pre>
<pre class="line before"><span class="ws">                </span>continue</pre>
<pre class="line current"><span class="ws">            </span>response = trafilatura.extract(downloaded)</pre>
<pre class="line after"><span class="ws">            </span>if not response:</pre>
<pre class="line after"><span class="ws">                </span>if self.error_on_missing:</pre>
<pre class="line after"><span class="ws">                    </span>raise ValueError(f&#34;Trafilatura fails to parse page: {url}&#34;)</pre>
<pre class="line after"><span class="ws">                </span>continue</pre>
<pre class="line after"><span class="ws">            </span>documents.append(Document(response))</pre></div>
</div>

<li><div class="frame" id="frame-140663172344832">
  <h4>File <cite class="filename">"/home/shubham/.local/lib/python3.10/site-packages/trafilatura/core.py"</cite>,
      line <em class="line">1050</em>,
      in <code class="function">extract</code></h4>
  <div class="source "><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span># put timeout signal in place</pre>
<pre class="line before"><span class="ws">    </span>if HAS_SIGNAL is True:</pre>
<pre class="line before"><span class="ws">        </span>timeout = config.getint(&#39;DEFAULT&#39;, &#39;EXTRACTION_TIMEOUT&#39;)</pre>
<pre class="line before"><span class="ws">        </span>if timeout &gt; 0:</pre>
<pre class="line current"><span class="ws">            </span>signal(SIGALRM, timeout_handler)</pre>
<pre class="line after"><span class="ws">            </span>alarm(timeout)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span># extraction</pre>
<pre class="line after"><span class="ws">    </span>try:</pre>
<pre class="line after"><span class="ws">        </span>document = bare_extraction(</pre></div>
</div>

<li><div class="frame" id="frame-140663172341136">
  <h4>File <cite class="filename">"/usr/lib/python3.10/signal.py"</cite>,
      line <em class="line">56</em>,
      in <code class="function">signal</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>return wrapper</pre>
<pre class="line before"><span class="ws">    </span>return decorator</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span>@_wraps(_signal.signal)</pre>
<pre class="line before"><span class="ws"></span>def signal(signalnum, handler):</pre>
<pre class="line current"><span class="ws">    </span>handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))</pre>
<pre class="line after"><span class="ws">    </span>return _int_to_enum(handler, Handlers)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>@_wraps(_signal.getsignal)</pre>
<pre class="line after"><span class="ws"></span>def getsignal(signalnum):</pre></div>
</div>
</ul>
  <blockquote>ValueError: signal only works in main thread of the main interpreter
</blockquote>
</div>

<div class="plain">
    <p>
      This is the Copy/Paste friendly version of the traceback.
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/flask/app.py&#34;, line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/flask/app.py&#34;, line 2531, in wsgi_app
    response = self.handle_exception(e)
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/flask/app.py&#34;, line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/flask/app.py&#34;, line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/flask/app.py&#34;, line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/flask/app.py&#34;, line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File &#34;/home/shubham/1-lang/fluff/intelliweb-GPT/example_usage.py&#34;, line 18, in answer_question
    result = generate_answer(query, use_serper_api)
  File &#34;/home/shubham/1-lang/fluff/intelliweb-GPT/intelliweb_GPT/generate.py&#34;, line 70, in generate_answer
    documents = reader.load_data(urls=urls)
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/llama_index/readers/web.py&#34;, line 102, in load_data
    response = trafilatura.extract(downloaded)
  File &#34;/home/shubham/.local/lib/python3.10/site-packages/trafilatura/core.py&#34;, line 1050, in extract
    signal(SIGALRM, timeout_handler)
  File &#34;/usr/lib/python3.10/signal.py&#34;, line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
</textarea>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/shubham/.local/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/shubham/.local/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/shubham/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shubham/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shubham/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shubham/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/shubham/1-lang/fluff/intelliweb-GPT/example_usage.py", line 18, in answer_question
    result = generate_answer(query, use_serper_api)
  File "/home/shubham/1-lang/fluff/intelliweb-GPT/intelliweb_GPT/generate.py", line 70, in generate_answer
    documents = reader.load_data(urls=urls)
  File "/home/shubham/.local/lib/python3.10/site-packages/llama_index/readers/web.py", line 102, in load_data
    response = trafilatura.extract(downloaded)
  File "/home/shubham/.local/lib/python3.10/site-packages/trafilatura/core.py", line 1050, in extract
    signal(SIGALRM, timeout_handler)
  File "/usr/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter

```

**Comment by AdirthaBorgohain** [comment]
Looks like `trafilatura` has issues running with flask. We need to remove llama-index's reader and use our own reader. I have updated the repo now and it should be compatible with flask. Check and let me know! Thanks

**Comment by connorv001** [comment]
Now it shows me:
```
Using Google Web Search and searching for 'Super Mario Bros. movie box office performance'...!
Traceback (most recent call last):
  File "/root/intelliweb-GPT/example_usage.py", line 5, in <module>
    answer_dict = generate_answer(query, use_serper_api=True)
  File "/root/intelliweb-GPT/intelliweb_GPT/generate.py", line 83, in generate_answer
    urls = get_relevant_urls(search_query, "search")
  File "/root/intelliweb-GPT/intelliweb_GPT/generate.py", line 59, in get_relevant_urls
    for r in response['organic'][:7]:
KeyError: 'organic'
```

**Comment by AdirthaBorgohain** [comment]
That's weird. It's working for me. Did you add the serper API key to the .env file?

**Comment by connorv001** [comment]
Works now :) thank you
